[en]
title = "Keisuke Hattori"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[jp]
title = "服部 圭介"
description = """
青山学院大学 経営学部 教授
"""
contentDir = "content/jp" 
weight = 2
LanguageName = "日本語"