  [[main]]
  name = "ホーム"
  identifier = "main"
  weight = 100
  url = "/jp/"

  [[main]]
  name = "投稿"
  weight = 200
  identifier = "posts"
  url = "/jp/post/"

  [[main]]
  name = "研究業績"
  weight = 300
  identifier = "pub"
  url = "/jp/pub/"

  [[main]]
  name = "コンタクト"
  weight = 400
  identifier = "contact"
  url = "/jp/contact/"