  [[main]]
  name = "ホーム"
  identifier = "home"
  weight = 100
  url = "/jp/"

  [[main]]
  name = "アーカイブ"
  weight = 500
  identifier = "posts"
  url = "/jp/post/"

  [[main]]
  name = "研究業績"
  weight = 300
  identifier = "pub"
  url = "/jp/pub/"

  [[main]]
  name = "プロフィール"
  weight = 200
  identifier = "profile"
  url = "/jp/profile/"
  
    [[main]]
  name = "講義/ゼミ"
  weight = 400
  identifier = "edu"
  url = "/jp/edu/"