title = "Keisuke Hattori"
author = "Keisuke Hattori"
#copyright = "2020-2021"
description = """
Professor
School of Business
Aoyama Gakuin University, JAPAN
"""
profilePicture = "images/profile.jpg"
keywords = ""
contentratio = 0.65
favicon = "favicons/"
# example ["css/custom.css"]
customCss = ["css/custom.css"]
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/keisuke-hattori-889a4419b/"

[[socialIcons]]
icon = "fas fa-lightbulb"
title = "Ideas"
url = "https://ideas.repec.org/f/pha391.html"

[[socialIcons]]
icon = "fab fa-researchgate"
title = "Research Gate"
url = "https://www.researchgate.net/profile/Keisuke-Hattori-2"

[[socialIcons]]
icon = "fas fa-file"
title = "Note"
url = "https://note.com/hattorizemi"