baseURL = "https://httrksk.github.io/"
languageCode = "ja-jp"
title = "Keisuke Hattori"
theme = "anatole"
summaryLength = 50
enableEmoji = true
enableRobotsTXT = true
canonifyurls = true
publishDir = "docs"

[params]
  title = "Keisuke Hattori"
  author = "Keisuke Hattori"
  gtagId = "G-N4EYQRJ4R7"
  googleAnalytics = "G-N4EYQRJ4R7"

# Enable Disqus
# disqusShortname = ""

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[languages]
  [languages.jp]
    languageName = "日本語"
    weight = 2
    contentDir = "content/jp"
    [languages.jp.params]
      description = "青山学院大学 経営学部 教授"
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"