baseURL = "https://httrksk.github.io/"
languageCode = "ja-jp"
title = "Keisuke Hattori"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
canonifyurls = true
publishDir = "docs"


# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
