baseURL = "https://httrksk.github.io/"
languageCode = "ja-jp"
title = "Keisuke Hattori"
theme = "anatole"
summaryLength = 50
enableEmoji = true
enableRobotsTXT = true
canonifyurls = true
publishDir = "docs"

[params]
title = "Keisuke Hattori"
author = "Keisuke Hattori"



# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "G-N4EYQRJ4R7"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
